/**
 * Smoke test in a browser-like environment.
 *
 * Needed because selftest.ts runs in Node, where Buffer, process and
 * global exist. The app crashed in the browser on its very first @ton/core import, while all
 * checks were green. Here the environment is deliberately stripped of Node
 * globals — exactly like a browser.
 */
import { readFileSync } from 'fs';
import { JSDOM, VirtualConsole } from 'jsdom';

const bundle = readFileSync(new URL('./dist-smoke/smoke.js', import.meta.url), 'utf8');

const errors = [];
const virtualConsole = new VirtualConsole();
virtualConsole.on('jsdomError', (e) => errors.push(e.message + (e.detail ? `\n${e.detail}` : '')));
virtualConsole.on('error', (...a) => errors.push(a.join(' ')));

const dom = new JSDOM('<!doctype html><html><body><div id="root"></div></body></html>', {
    runScripts: 'dangerously',
    pretendToBeVisual: true,
    url: 'http://localhost/',
    virtualConsole,
});

const { window } = dom;

// A real browser has this, jsdom doesn't. Everything else is deliberately
// NOT provided: Node globals must be absent, that's the whole point.
//
// We pass through Node's fetch, not a stub: TonConnect downloads the
// manifest through it, and a fake would hide real load errors.
window.matchMedia ??= () => ({
    matches: false,
    addEventListener() {},
    removeEventListener() {},
    addListener() {},
    removeListener() {},
});
window.scrollTo ??= () => {};
window.fetch ??= (...args) => fetch(...args);
window.Headers ??= Headers;
window.Request ??= Request;
window.Response ??= Response;

if (typeof window.Buffer !== 'undefined') {
    console.log('  WARNING: Buffer leaked into the environment — the test isn\'t conclusive');
}

const script = window.document.createElement('script');
script.textContent = bundle;
window.document.body.appendChild(script);

// Short by default — the test shouldn't depend on a live network. SMOKE_WAIT
// lets you wait for real data when you want to see the result.
await new Promise((r) => setTimeout(r, Number(process.env.SMOKE_WAIT ?? 1500)));

const root = window.document.getElementById('root');
const html = root?.innerHTML ?? '';

let failed = 0;
function check(name, cond, extra = '') {
    console.log(cond ? `  ok   ${name}` : `  FAIL ${name} ${extra}`);
    if (!cond) failed++;
}

console.log('running the app in a browser-like environment');
check('no unhandled errors', errors.length === 0, `\n${errors.join('\n')}`);
check('React rendered the tree', html.length > 0);
// We check by structure, not text: the copyright changes often, and a test
// that fails on a wording change only gets in the way. The anchors are data-attributes:
// class names are now generated by CSS Modules and are hashed in the markup.
// Until the protocol is read there's no page at all — a splash covers it.
// In a browser-like environment with no network the app usually lands on it,
// so we check not "one thing must exist" but that the state is valid:
// either the splash or an already-rendered page with a header.
const loading = html.includes('data-loader');
if (loading) {
    check('a splash covers the page while loading', html.includes('aria-busy="true"'));
} else {
    check('the heading is rendered', html.includes('data-lede'));
    check('the wallet button is mounted', html.includes('data-tc-connect-button'));
    // The chain switcher: both tabs must be present, and an undeployed
    // chain is marked, so expectations are set before the click, not after.
    // Solana is deployed on devnet, so it no longer has the soon mark —
    // we only check that both tabs are present.
    check(
        'the chain switcher is rendered',
        html.includes('TON') && html.includes('Solana'),
    );
    // There's more than one pool on TON, and choosing between them is the only way
    // to reach the second. A tab missing from the markup makes a pool
    // unreachable even with fully working contracts.
    check(
        'the pool switcher is rendered',
        html.includes('aria-label="Pool"') || html.includes('tsTON'),
    );
    // The Solana wallet button must be on its tab — without it
    // connecting is impossible, and you'd only find out by clicking.
    check(
        'a wallet button exists for both chains',
        html.includes('data-tc-connect-button') || html.includes('Connect Wallet'),
    );
}
// What exactly should be on the page depends on whether the protocol is deployed
// on the selected chain. Both states are valid, but one must not be swapped for the other:
// without addresses the interface must say so honestly, not draw zeros.
// We take the network from where the build takes it — .env. Reading
// process.env won't do: vite inlines the variables into the bundle itself, and in the
// node process they're absent, so the test would compare against the wrong network.
function envNetwork() {
    try {
        const env = readFileSync(new URL('./.env', import.meta.url), 'utf8');
        const m = env.match(/^\s*VITE_NETWORK\s*=\s*(\S+)/m);
        return m ? m[1] : 'testnet';
    } catch {
        return 'testnet';
    }
}

const network = envNetwork();
const deployed = JSON.parse(
    readFileSync(new URL(`./src/deployments/${network}.json`, import.meta.url), 'utf8'),
).vault !== null;
console.log(`  (network: ${network}, deployed: ${deployed ? 'yes' : 'no'})`);

if (deployed) {
    // By snapshot time the app can be in any of three valid
    // states — whichever it reaches in the allotted time. The network here is real,
    // so guessing is pointless: we list all three and check that
    // the app ended up in one of them, not stuck on an empty page.
    const states = {
        'reading state': loading,
        'showed a network error with a retry button': html.includes('Retry'),
        'rendered tranches': html.includes('data-waterfall'),
    };
    const reached = Object.entries(states).find(([, v]) => v)?.[0];
    check(`the app reached protocol interaction (${reached ?? 'no state'})`, Boolean(reached));
    check('no deploy instructions — the protocol is deployed', !html.includes('not deployed'));
} else {
    check('with no addresses it shows instructions, not made-up data', html.includes('not deployed'));
    check('no tranche cards — nothing to draw', !html.includes('data-waterfall'));
}

if (process.env.SMOKE_PROBE) {
    const t = html.replace(/<svg[\s\S]*?<\/svg>/g, '').replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ');
    console.log('  TEXT:', JSON.stringify(t.slice(0, 400)));
}

if (process.env.SMOKE_DUMP) {
    // Without stripping svg the whole dump goes to the wallet icon.
    const text = html
        .replace(/<svg[\s\S]*?<\/svg>/g, '')
        .replace(/<[^>]+>/g, ' ')
        .replace(/\s+/g, ' ');
    console.log('\n--- page text ---\n' + text.slice(0, 900));
}

dom.window.close();
console.log(failed === 0 ? '\nthe app starts' : `\nfailed: ${failed}`);
process.exit(failed === 0 ? 0 : 1);
